#!/usr/bin/env tsx
/**
 * Emit THIRD_PARTY_LICENSES.md by inspecting workspace dependencies.
 * Stub implementation — replaced once real dependencies are wired in.
 */
const out = [
  "# Third-Party Licenses",
  "",
  "_Generated by `scripts/generate-third-party-licenses.ts`._",
  "",
  "No third-party runtime dependencies are bundled yet.",
  "",
];

process.stdout.write(out.join("\n"));
